name: riskmodel
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - blas=1.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.01.04
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cpuonly=2.0
  - expat=2.7.3
  - filelock=3.20.0
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.2
  - idna=3.11
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9f
  - khronos-opencl-icd-loader=2024.10.24
  - lcms2=2.16
  - lerc=3.0
  - libblas=3.9.0
  - libboost=1.88.0
  - libcblas=3.9.0
  - libdeflate=1.17
  - libexpat=2.7.3
  - libffi=3.4.4
  - libiconv=1.18
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblightgbm=4.6.0
  - libpng=1.6.50
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libzlib=1.3.1
  - lightgbm=4.6.0
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - networkx=3.6.1
  - numpy-base=2.0.1
  - opencl-headers=2025.06.13
  - openjpeg=2.5.2
  - openssl=3.6.0
  - pip=25.3
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.11.14
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - requests=2.32.5
  - setuptools=80.9.0
  - sqlite=3.51.1
  - sympy=1.14.0
  - tbb=2021.8.0
  - tk=8.6.15
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - typing_extensions=4.15.0
  - ucrt=10.0.22621.0
  - urllib3=2.6.3
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - duckdb==1.4.3
      - fonttools==4.61.1
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - llvmlite==0.46.0
      - matplotlib==3.10.8
      - numba==0.63.1
      - numpy==2.3.5
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.1.0
      - pyarrow==22.0.0
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - shap==0.50.0
      - six==1.17.0
      - slicer==0.0.8
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - tzdata==2025.3
      - xgboost==3.1.3
prefix: D:\MiniConda\envs\riskmodel
